CREATE TABLE room (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  is_reserved BIT NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE reservation (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  reservation_start_date DATE NOT NULL,
  reservation_end_date DATE NOT NULL,
  room_id BIGINT(20) NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FKm8xumi0g23038cw32oiva2ymw FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;